### ISSUE TITLE
Uncaught TypeError: this.editor.getBuffer is not a function

### ISSUE THREAD

**Issue by dagrende** [eqot/atom-broadcast#12]
[Enter steps to reproduce below:]

1. opened an MD file
2. Packages > Markdown Preview > Toggle Preview
3. Clicked in the md preview pane
4. Packages > Broadcast > Start
5. Got this error (it actually serves an empty web page on localhost:8000)

**Atom Version**: 1.13.1
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.3
**Thrown From**: [broadcast](https://github.com/eqot/atom-broadcast) package, v0.3.14

### Stack Trace

Uncaught TypeError: this.editor.getBuffer is not a function

```
At /Users/dag/.atom/packages/broadcast/lib/broadcast-target.coffee:27

TypeError: this.editor.getBuffer is not a function
    at new BroadcastTarget (/Users/dag/.atom/packages/broadcast/lib/broadcast-target.coffee:27:9)
    at BroadcastServer.module.exports.BroadcastServer.start (/Users/dag/.atom/packages/broadcast/lib/broadcast-server.coffee:23:19)
    at Object.start (/Users/dag/.atom/packages/broadcast/lib/broadcast.coffee:36:13)
    at atom-workspace.atom.commands.add.broadcast:start (/Users/dag/.atom/packages/broadcast/lib/broadcast.coffee:29:10)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1175:28)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:319:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:17.8.0 broadcast:start (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:05.8.0 markdown-preview:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:00.0 broadcast:start (div.markdown-preview.native-key-bindings)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "spell-check"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      ".pioenvs",
      ".piolibdeps",
      ".clang_complete",
      ".gcc-flags.json"
    ],
    "telemetryConsent": "limited",
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.17 (inactive)
autocomplete-clang, v0.10.0 (active)
broadcast, v0.3.14 (active)
build, v0.67.0 (active)
busy, v0.7.0 (active)
emmet, v2.4.3 (active)
file-icons, v2.0.13 (active)
language-ini, v1.17.0 (active)
language-vue, v0.21.2 (active)
linter, v1.11.21 (active)
linter-gcc, v0.7.1 (active)
log-vars, v0.0.0 (inactive)
markdown-pdf, v1.5.0 (inactive)
merge-conflicts, v1.4.4 (active)
minimap, v4.26.8 (active)
platformio-ide, v1.7.2 (active)
platformio-ide-terminal, v2.2.2 (active)
tool-bar, v1.0.1 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (active)
atom-light-ui, v0.46.0 (active)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (inactive)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (inactive)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.3 (active)
metrics, v1.1.3 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (inactive)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by james-logan** [comment]
+1

**Comment by mbnissen** [comment]
+1

**Comment by bllllent** [comment]
+1

**Comment by lindison** [comment]
To workaround or resolve this issue, install the following package:  
`markdown-preview-plus`

https://atom.io/packages/markdown-preview-plus

**Comment by dagrende** [comment]
No, markdown-preview-plus doesn't solve the problem. Markdown-preview-plus is just a much better markdown-preview. 
My use for atom-broadcast was to see the preview on my second screen. I have not found any way to get an Atom tab into a separate screen. If that would be possible, then markdown-preview-plus would be an alternative for me.

**Comment by eqot** [comment]
I believe that this issue has been fixed in atom-broadcast v0.4.0 with the commit below.

  https://github.com/eqot/atom-broadcast/commit/b750a2cc6f6a53958bd1bf1a51baf627017cdf97

**Comment by jpluimers** [comment]
@eqot it solved it for Markdown, but doesn't solve it for [reStructuredText Preview Pandoc](https://atom.io/packages/rst-preview-pandoc) where it generates the an error using `broadcast 0.4.0`.

Since your commit fixes rendered Markdown broadcasting, I've submitted the reStructuredText issue as a separate one: https://github.com/eqot/atom-broadcast/issues/13
